name: tox

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    tox-test:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python:
                    - {version: '3.12', env: py312}
                    - {version: '3.13', env: py313}
                    - {version: '3.14', env: py314}
                test_mode: [0, 1]
        runs-on: ${{ matrix.os }}
        env:
            TOXENV: ${{ matrix.python.env }}
            RUN_INTEGRATION_TESTS: ${{ matrix.test_mode }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python.version }}
            - run: pip install tox
            - run: pip install codecov
            - run: pip install slugs
            - run: python3 setup.py install
            - run: ./.travis/run.sh
            - run: codecov
    tox-other:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: ['3.12', '3.13', '3.14']
                test: [pep8, bandit, docs]
        runs-on: ${{ matrix.os }}
        env:
            TOXENV: ${{ matrix.test }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python }}
            - run: pip install tox
            - run: pip install bandit
              if: ${{ matrix.test == 'bandit' }}
            - run: tox
